### ISSUE TITLE
Movement command stops after some time

### ISSUE THREAD

**Issue by aksiksi** [hypower-org/jkobuki-2#3]
After I send a baseControl command to the Kobuki, the robot stops after some time. Is this expected behavior? Does this mean that the command packet needs to be re-sent continuously? I looked through the docs but couldn't find any mention of this.

**Comment by drpjm** [comment]
Yes, this is expected behavior of the Kobuki robot. Its embedded controller shuts down if it does not receive commands after some set amount of time.
